name: Build

on: [pull_request]

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install build dependencies
        run: sudo apt install -y build-essential cmake clang-tidy libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libglew-dev libglm-dev zlib1g-dev
      - name: cmake
        run: cmake -DUSE_CLANG_TIDY=1 .
      - name: make
        run: make -j`nproc`
